### ISSUE TITLE
slow

### ISSUE THREAD

**Issue by chengweige** [AlanLuSun/High-quality-ellipse-detection#5]
------read image------
The number of output arc-support line segments: 1503
The number of arc-support groups:1251
The number of initial ellipses：1681 
The number of ellipse candidates: 1679 
edge pixel number: 341782
the time of generating ellipse candidates:2.15
-----------------------------------------------------------
running time:80.316s
draw detected ellipses

ellipses =

   1.0e+03 *

    0.8264    0.7874    0.0494    0.0342    0.0314
    0.3918    0.5093    0.0527    0.0275   -0.0105
    1.2749    1.3484    0.3701    0.2263    0.0015
    0.7155    1.3133    0.0864    0.0545   -0.0086
    1.2757    1.3691    0.3612    0.2106    0.0009

The total number of detected ellipses：5

image size: 2592x1944

**Comment by AlanLuSun** [comment]
what is wrong?

**Comment by AlanLuSun** [comment]
You can try again by downsizing the image with 2 ~ 3 times
